### ISSUE TITLE
AttributeError: module 'hadamard_cuda' has no attribute 'hadamard_transform'

### ISSUE THREAD

**Issue by Ashokvardhan** [HazyResearch/structured-nets#4]
Hi,

It seems I am unable to use the `hadamard_transform_cuda` function for some reason. I checked that there is no issue with the installation. When I ran `python setup.py install`, I get the following:

``running install
running bdist_egg
running egg_info
writing hadamard_cuda.egg-info/PKG-INFO
writing dependency_links to hadamard_cuda.egg-info/dependency_links.txt
writing top-level names to hadamard_cuda.egg-info/top_level.txt
reading manifest file 'hadamard_cuda.egg-info/SOURCES.txt'
writing manifest file 'hadamard_cuda.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
warning: install_lib: 'build/lib' does not exist -- no Python modules to install

creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying hadamard_cuda.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying hadamard_cuda.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying hadamard_cuda.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying hadamard_cuda.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating 'dist/hadamard_cuda-0.0.0-py3.6.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing hadamard_cuda-0.0.0-py3.6.egg
Copying hadamard_cuda-0.0.0-py3.6.egg to /home/ashok/anaconda3/envs/okay/lib/python3.6/site-packages
Adding hadamard-cuda 0.0.0 to easy-install.pth file

Installed /home/ashok/anaconda3/envs/okay/lib/python3.6/site-packages/hadamard_cuda-0.0.0-py3.6.egg
Processing dependencies for hadamard-cuda==0.0.0
Finished processing dependencies for hadamard-cuda==0.0.0``

However, when I access the function  `hadamard_transform_cuda` , I get the following error: 

`import torch
import hadamard_cuda
from hadamard import *
a = torch.randn(5,2).cuda()

hadamard_transform_cuda(a)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ashok/reed_muller/Neural_Plotkin/reed_muller_modules/hadamard.py", line 68, in hadamard_transform_cuda
    output = HadamardTransformCuda.apply(u)
  File "/home/ashok/reed_muller/Neural_Plotkin/reed_muller_modules/hadamard.py", line 49, in forward
    return hadamard_cuda.hadamard_transform(u)
AttributeError: module 'hadamard_cuda' has no attribute 'hadamard_transform'`

My conda environment has the following configurations: ` python=3.6, pytorch 1.0.0, cudatoolkit=10.0, gcc (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609`

**Comment by tridao** [comment]
We try to check if CUDA is available before compiling. If it isn't then the extension isn't compiled.
So you need to compile it on a machine where CUDA is available (e.g. `nvcc` is installed).
The check is here https://github.com/HazyResearch/structured-nets/blob/master/pytorch/structure/hadamard_cuda/setup.py#L8.
Can you verify that this check evaluates to True on your machine?

**Comment by Ashokvardhan** [comment]
> We try to check if CUDA is available before compiling. If it isn't then the extension isn't compiled.
> So you need to compile it on a machine where CUDA is available (e.g. `nvcc` is installed).
> The check is here https://github.com/HazyResearch/structured-nets/blob/master/pytorch/structure/hadamard_cuda/setup.py#L8.
> Can you verify that this check evaluates to True on your machine?

Thanks a lot! I somehow missed this. Now I am able to install it. However, I am facing another issue. The function `hadamard_transform_cuda` is not working for size 2 for some reason. I get the following error: 

`from hadamard import *
hadamard_transform_cuda(torch.randn(5,2).to(device))
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
~/anaconda3/envs/torch/lib/python3.7/site-packages/IPython/core/formatters.py in __call__(self, obj)
    700                 type_pprinters=self.type_printers,
    701                 deferred_pprinters=self.deferred_printers)
--> 702             printer.pretty(obj)
    703             printer.flush()
    704             return stream.getvalue()

~/anaconda3/envs/torch/lib/python3.7/site-packages/IPython/lib/pretty.py in pretty(self, obj)
    392                         if cls is not object \
    393                                 and callable(cls.__dict__.get('__repr__')):
--> 394                             return _repr_pprint(obj, self, cycle)
    395 
    396             return _default_pprint(obj, self, cycle)

~/anaconda3/envs/torch/lib/python3.7/site-packages/IPython/lib/pretty.py in _repr_pprint(obj, p, cycle)
    698     """A pprint that just redirects to the normal repr function."""
    699     # Find newlines and replace them with p.break_()
--> 700     output = repr(obj)
    701     lines = output.splitlines()
    702     with p.group():

~/anaconda3/envs/torch/lib/python3.7/site-packages/torch/tensor.py in __repr__(self)
    151     def __repr__(self):
    152         # All strings are unicode in Python 3.
--> 153         return torch._tensor_str._str(self)
    154 
    155     def backward(self, gradient=None, retain_graph=None, create_graph=False):

~/anaconda3/envs/torch/lib/python3.7/site-packages/torch/_tensor_str.py in _str(self)
    369 def _str(self):
    370     with torch.no_grad():
--> 371         return _str_intern(self)

~/anaconda3/envs/torch/lib/python3.7/site-packages/torch/_tensor_str.py in _str_intern(self)
    349                     tensor_str = _tensor_str(self.to_dense(), indent)
    350                 else:
--> 351                     tensor_str = _tensor_str(self, indent)
    352 
    353     if self.layout != torch.strided:

~/anaconda3/envs/torch/lib/python3.7/site-packages/torch/_tensor_str.py in _tensor_str(self, indent)
    239         return _tensor_str_with_formatter(self, indent, summarize, real_formatter, imag_formatter)
    240     else:
--> 241         formatter = _Formatter(get_summarized_data(self) if summarize else self)
    242         return _tensor_str_with_formatter(self, indent, summarize, formatter)
    243 

~/anaconda3/envs/torch/lib/python3.7/site-packages/torch/_tensor_str.py in __init__(self, tensor)
     87 
     88         else:
---> 89             nonzero_finite_vals = torch.masked_select(tensor_view, torch.isfinite(tensor_view) & tensor_view.ne(0))
     90 
     91             if nonzero_finite_vals.numel() == 0:

RuntimeError: CUDA error: invalid configuration argument`

However, it's working finely for any other size which is a power of two. The following is the output for size 8:
`hadamard_transform_cuda(torch.randn(5,8).to(device))

tensor([[-2.2053, -1.1619,  0.0141, -5.2018, -0.9314, -0.8693,  7.1832,  0.6044],
        [ 3.4769, -1.4690,  5.0574,  3.2446,  1.0288, -4.8183, -2.8624, -2.4191],
        [ 1.8221,  2.3411, -4.1955,  0.0497,  2.8590,  0.4748, -0.8683, -2.5792],
        [-2.2661,  4.4741, -0.1341,  0.3474,  2.3634, -1.6993, -0.8374,  0.3368],
        [-3.9063, -0.5574, -2.2716,  1.1861, -1.7847,  3.7164,  2.6546,  0.8866]],
       device='cuda:0')`

**Comment by tridao** [comment]
I've just pushed a commit to fix the case n == 2. Thanks for reporting it.
Can you try now?
